---
# create vpc 10.0.0./16
# in my case i have 3 availability zone. though, i create subnets for
# each Availability zone
# create 3 public subnets and 3 private subnets each AZ
# create internet gateway for public subnets
# IAM key is passed from environmental variables
- name: create VPC & public private subnets for each AZ
  hosts: control
  connection: local
  gather_facts: false
  roles:
    - vpc
