---
# tasks file for instance
- include_vars: ./group_vars/all.yml

- name: find ami-id based on region, here I'm passing region from ~./aws/config
  ec2_ami_find:
    name: "ubuntu/images/ebs/ubuntu-trusty-14.04-amd64-server-*"
    owner: aws-marketplace
    aws_region: "{{default_region}}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: result_ami


- name: create ec2 instance 3 with demo tag
  ec2:
    key_name: "{{key_name}}"
    group: LAMP_Stack
    instance_type: t2.micro
    #region=us-east-1  ami-c998b6b2
    image: "{{ result_ami.results[0].ami_id }}"
    wait: yes
    exact_count: 3
    count_tag:
      Name: LAMP_Stack
    instance_tags:
      Name: "{{item}}"
      with_item:
        - webserver
        - mysql
        - lb
    termination_protection: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2

- name: add instance IP to hosts group
  add_host: hostname={{item.public_ip}} groups=ec2hosts
  loop: "{{ec2.instances}}"
